### PR TITLE
use sync.RWMutex when masterNode changes

### PR DESCRIPTION
**Pull request by aszxqw**
https://github.com/chrislusf/weed-fs/issues/74

### CODE REVIEW

**Comment by chrislusf** [comment]
No need for this. Only one goroutine will be changing this value.

**Comment by aszxqw** [comment]
But other goroutine will read this value.

**Comment by aszxqw** [comment]
I wrote two programs to check if safe. 

https://github.com/aszxqw/practice/blob/master/go/rwmutex/notlock.go
https://github.com/aszxqw/practice/blob/master/go/rwmutex/lock.go

It turns out `notlock.go` will go wrong() after running 2 minutes. 
And `lock.go` is always running ok .

So I think it is not safe, when one goroutine is writing a variable and other goroutines read it  without locking.
So I think you need this `pull request`.

**Comment by chrislusf** [comment]
I do not understand the test. Does it mean g.a will be read wrongly? Wrongly means totally wrong data or just stale data? Stale data is fine for current bug, since the thread to check correct master node only runs every few seconds.

**Comment by aszxqw** [comment]
Not about stale data, it is about something unexpected will happen when concurrent access without `sync`.
If it is safe for one goroutine writing when another goroutine reading without `sync`,
so what do you think of sync.RWMutex is made for ?

**Comment by aszxqw** [comment]
"Programs that modify data being simultaneously accessed by multiple goroutines must serialize such access.
To serialize access, protect the data with channel operations or other synchronization primitives such as those in the sync and sync/atomic packages."
> https://golang.org/ref/mem

**Comment by chrislusf** [comment]
We have one thread that's basically swapping one string value to another. This is a copy on write operation.  Maybe check this page, which explains better than I do: http://en.wikipedia.org/wiki/Copy-on-write

**Comment by aszxqw** [comment]
I know the conception of COW,  but I don't know what is the relation between COW and this concurrency-safety issue.

I guess your thoughts is "it is safe because masterNode is a **string** ", isn't it ?
So I wanna ask you a question , is it safe when masterNode is a **int** or **map** ?

**Comment by jan4984** [comment]
i got "Failed to write to replicas for volume 3" too and it leads me here. not know much to the seaweedfs source but about the concurrency-safety, I think @yanyiwu is right, we need lock.

**Comment by chrislusf** [comment]
Please share your logs, setups.

**Pull request closed without merging**
