### PR TITLE
use sync.RWMutex when masterNode changes

### PR DESCRIPTION
**Pull request by aszxqw**
It needs lock.

https://groups.google.com/forum/?hl=zh-CN#!topic/golang-nuts/zyQnord8hyc

### CODE REVIEW

**Comment by chrislusf** [comment]
Even the race happens, it would not impact the system since it's in a transition period.

However, I still do not see it's possible to have any data race related error related to this. It's just changing a string pointer, which is one cpu operation. But I do not know much about Go deep internals. Having a reproducible test case would be more convincing.

**Comment by aszxqw** [comment]
1.
`Even the race happens, it would not impact the system since it's in a transition period.`
When the race happens, your process will be dead.  

2.  `It's just changing a string pointer, which is one cpu operation. ` You mean a pointer change is atomic operation ? Are you sure ?

I just hope this project to be more stable, avoid potential error happening.
But now that you really think it is no need to do it, so let's forget it and move on.

**Comment by chrislusf** [comment]
Looks like you are winning on the mailing list. Reopening this. But it still has compilation error. Please check again.

**Comment by aszxqw** [comment]
Now it's ok.

**Comment by chrislusf** [comment]
Try to use atomic.Value to simplify this if possible.

**Comment by aszxqw** [comment]
Nice suggestion, but I am not familiar with atomic.Value, maybe someone else can do it.

**Pull request merged**
