### PR TITLE
helpHander

### PR DESCRIPTION
**Pull request by aszxqw**
helpHandler for `curl "http://127.0.0.1:9333/help"`,
I think `/help` is more convenient, Although its output is rough now.

### CODE REVIEW

**Comment by chrislusf** [comment]
This is a great idea! However, I think the change is not ready yet.
1. There are 3 commits. Only the last commit is related to the change. In the future, please do not mix unrelated changes together.
2. The design for the helpHandler needs adjustment. It still needs a specific call to add the help content. This can easily lead to inconsistent help content. It'll be great to use some annotation or convention to add the help content, so that developers can adjust help content close to where the actual code are.

**Comment by aszxqw** [comment]
1. I know the other two commits is not related with `helpHanlder`, but they are useful for me to read and understand codes, so I make they in my fork repo, I pr(pull request) them because I think they are harmless and maybe useful for the other people. but if you think they are not helpful, it is OK, I can follow your point of view.
2. I know the helpHandler is rough , but I don't think everyone persion pr the commit when the commit reach 100% perfect. Although it is rough, but It is helpful for me and other users, after all, not everyone is familiar enough with your codes and docs.

If you still think these commits should not be merged into master,  please feel free to close this pr, it is OK, I can understand.

**Comment by aszxqw** [comment]
1. I know the other two commits are not related with `helpHanlder`, but they are useful for me to read and understand codes, so I think it may be helpful to other people.
2. I know the `helpHandler` is rough now, but I don't think every commit must not be pr(pull request) until it is 100% perfect. I just think it is useful for me and other people, after all, not everyone is familiar with this project.

If you surely think it should not be merged into master, please feel free to close this pr, it is OK.

**Comment by chrislusf** [comment]
I will close this PR. Please create another one for the first 2 commits. Also, please keep up your effort for the "help" handler. Need to think of a neat way to annotate a handler function.

**Pull request closed without merging**
